adjust build

diff --git a/.github/workflows/veracode-build.yml b/.github/workflows/veracode-build.yml
--- a/.github/workflows/veracode-build.yml
+++ b/.github/workflows/veracode-build.yml
@@ -51,21 +51,36 @@ jobs:
         path: app.zip
 
   register:
-    runs-on: ubuntu-latest
-    name: register
-    needs: build
-    steps:
-      - name: Register build
-        id: register-build
-        uses: veracode/github-actions-integration-helper@v0.1.7
-        with:
-          action: registerBuild
-          token: ${{ github.event.client_payload.token }}
-          appname: ${{ github.event.client_payload.user_config.profile_name }}
-          source_repository: ${{ github.event.client_payload.repository.full_name }}
-          check_run_id: ${{ github.run_id }}
-          check_run_name: ${{ github.workflow }}
-          head_sha: ${{ github.event.client_payload.sha }}
-          event_type: ${{ github.event.client_payload.event_type }}
-          branch: ${{ github.event.client_payload.user_config.sandbox_scan.branch }}
-          issue_trigger_flow: ${{ github.event.client_payload.user_config.issue_trigger_flow }}
+      runs-on: ubuntu-latest
+      name: register
+      needs: build
+
+      steps:
+        - name: Validate required payload fields
+          run: |
+            if [ -z "${{ github.event.client_payload.token }}" ]; then
+              echo "::error::Missing Veracode token"
+              exit 1
+            fi
+
+            if [ -z "${{ github.event.client_payload.repository.branch }}" ]; then
+              echo "::error::Missing repository branch in payload"
+              exit 1 
+            fi
+
+        - name: Register build
+          id: register-build
+          uses: veracode/github-actions-integration-helper@v0.1.9
+          with:
+            action: registerBuild
+            vid: ${{ secrets.VERACODE_API_ID }}
+            vkey: ${{ secrets.VERACODE_API_KEY }}
+            token: ${{ github.event.client_payload.token }}
+            appname: ${{ github.event.client_payload.user_config.profile_name }}
+            source_repository: ${{ github.event.client_payload.repository.full_name }}
+            check_run_id: ${{ github.run_id }}
+            check_run_name: ${{ github.workflow }}
+            head_sha: ${{ github.event.client_payload.sha }}
+            event_type: ${{ github.event.client_payload.event_type }}
+            branch: ${{ github.event.client_payload.repository.branch }}
+            issue_trigger_flow: ${{ github.event.client_payload.user_config.issue_trigger_flow }}
